[package]
name = "averages"
version = "0.1.0"
authors = ["jtempest"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
once_cell = "1.3"
num = "0.2"